# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='commentable',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u8bc4\u8bba'),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.SmallIntegerField(default=2, max_length=3, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=2048, null=True, verbose_name='\u6587\u7ae0\u6458\u8981'),
        ),
        migrations.AddField(
            model_name='blog',
            name='visitors',
            field=models.BigIntegerField(default=0, max_length=10, verbose_name='\u8bbf\u95ee\u91cf'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=32, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=80, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=480, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=64, verbose_name='\u79f0\u547c'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
