# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191214_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog', verbose_name='\u535a\u5ba2'),
        ),
    ]
